# Generated by Django 3.2 on 2022-04-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
