# Generated by Django 3.2 on 2022-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='name',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
