# Generated by Django 3.2 on 2022-05-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscribe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='name',
        ),
    ]
